version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01

    java:
      version: oraclejdk8

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "71:b1:3f:07:64:54:71:15:8a:3c:e4:da:bb:82:2c:ca"

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew website --refresh-dependencies

      - run:
          command: .circleci/publish.sh

workflows:
  version: 2
  publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
