version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02

    java:
      version: oraclejdk8

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ce:86:6c:fa:60:25:31:0b:28:ab:1a:05:9c:e9:c7:92"

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew website --refresh-dependencies

      - run:
          command: .circleci/publish.sh

workflows:
  version: 2
  publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
