version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01

    java:
      version: oraclejdk8

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ce:86:6c:fa:60:25:31:0b:28:ab:1a:05:9c:e9:c7:92"

      - checkout

      - run: echo ignore-gh-branch

workflows:
  version: 2
  publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
