version: '3.8'

services:
    xtserver:
      image: httpd:2.4
      container_name: xmlcatdotorg
      ports:
        - 8818:80
      working_dir: /src
      volumes:
        - ../build/website:/usr/local/apache2/htdocs
      stdin_open: true
      tty: true
      networks:
        - external_net

networks:
  external_net: {}
